## Lab 5

In [1]:
import numpy as np

def input_matrix(m, n):
    A = []
    for i in range(m):
        row = list(map(int, input().split()))
        if len(row) != n:
            print("Invalid number of elements in row")
            exit(0)
        A.append(row)
    return np.array(A)


print("Welcome to Matrix Calculator")

m1, n1 = map(int, input("\nDimensions of Matrix A (space-separated): ").split())
print(f"Enter the elements of Matrix A ({n1}-col, {m1}-row): ")
mat1 = input_matrix(m1, n1)

m2, n2 = map(int, input("\nDimensions of Matrix B (space-separated): ").split())
print(f"Enter the elements of Matrix B ({n2}-col, {m2}-row): ")
mat2 = input_matrix(m2, n2)

print("\nOperations related to Matrix:")
print("  1. Matrix Addition")
print("  2. Matrix Subtraction")
print("  3. Scalar Matrix Multiplication")
print("  4. Elementwise Matrix Multiplication")
print("  5. Matrix Multiplication")
print("  6. Matrix Transpose")
print("  7. Trace of a Matrix")
print("  8. Solve System of Linear Equations")
print("  9. Determinant")
print(" 10. Inverse")
print(" 11. Singular Value Decomposition")
print(" 12. Eigen Value")
print(" 13. Search an element in a Matrix")
print(" 14. Difference of Sum of Upper and Lower Triangular Matrix")
print(" 15. Exit")

while True:
    opt = int(input("\nEnter your choice: "))
    if opt == 15:
        print("Exiting...")
        break

    if opt in (1, 2, 4):
        if m1 != m2 or n1 != n2:
            print("Invalid dimensions: Dimensions of both matrices must be same")
            continue
    elif opt == 5:
        if n1 != m2:
            print("Invalid dimensions: Matrix Multiplication not possible")
            continue
    
    if opt == 1:
        print("Matrix Addition: ")
        print(np.add(mat1, mat2))
    
    elif opt == 2:
        print("Matrix Subtraction: ")
        print(np.subtract(mat1, mat2))
    
    elif opt == 3:
        scalar = int(input("Enter the scalar value: "))
        print("Scalar Matrix Multiplication: ")
        print("Matrix A:", np.multiply(scalar,mat1), sep="\n")
        print("Matrix B:", np.multiply(scalar,mat2), sep="\n")
    
    elif opt == 4:
        print("Elementwise Matrix Multiplication: ")
        print(np.multiply(mat1, mat2))
    
    elif opt == 5:
        print("Matrix Multiplication: ")
        print(np.matmul(mat1, mat2))
    
    elif opt == 6:
        print("Matrix Transpose: ")
        print("Matrix A:", np.transpose(mat1), sep="\n")
        print("Matrix B:", np.transpose(mat2), sep="\n")
    
    elif opt == 7:
        print("Trace of a Matrix:")
        print("Matrix A: ", end="")
        if m1 == n1:
            print(np.trace(mat1))
        else:
            print("Not a Square Matrix")
        print("Matrix B: ", end="")
        if m2 == n2:
            print(np.trace(mat2))
        else:
            print("Not a Square Matrix")
    
    elif opt == 8:
        print("Solve System of Linear Equations:")
        print("\nFor Matrix A: ")
        if m1 != n1:
            print("Solution not possible: m != n")
            continue
        b = np.array(list(map(int, input(f"Enter the elements of vetcor b (len={m1}): ").split())))
        if len(b) != m1:
            print("Invalid Dimensions: len(b) != m")
        else:
            print("Solution:", np.linalg.solve(mat1, b))
        print("\nFor Matrix B: ")
        if m2 != n2:
            print("Solution not possible: m != n")
            continue
        b = np.array(list(map(int, input(f"Enter the elements of vetcor b (len={m2}): ").split())))
        if len(b) != m2:
            print("Invalid Dimensions: len(b) != m")
        else:
            print("Solution:", np.linalg.solve(mat2, b))
    
    elif opt == 9:
        print("Determinant:")
        print("Matrix A: ", end="")
        if m1 == n1:
            print(np.linalg.det(mat1))
        else:
            print("Not a Square Matrix")
        print("Matrix B: ", end="")
        if m2 == n2:
            print(np.linalg.det(mat2))
        else:
            print("Not a Square Matrix")
    
    elif opt == 10:
        print("Inverse: ")
        print("Matrix A: ")
        if m1 == n1:
            if np.linalg.det(mat1) == 0:
                print("Inverse not possible: Determinant = 0")
            else:
                print(np.linalg.inv(mat1))
        else:
            print("Not a Square Matrix")
        print("Matrix B: ")
        if m2 == n2:
            if np.linalg.det(mat2) == 0:
                print("Inverse not possible: Determinant = 0")
            else:
                print(np.linalg.inv(mat2))
        else:
            print("Not a Square Matrix")
    
    elif opt == 11:
        print("Singular Value Decomposition: ")
        print("Matrix A: ")
        if m1 != n1:
            print("Not a Square Matrix")
        else:
            U, S, V = np.linalg.svd(mat1)
            print("U:", U, sep="\n")
            print("S:", S, sep="\n")
            print("V:", V, sep="\n")
        print("Matrix B: ")
        if m2 != n2:
            print("Not a Square Matrix")
        else:
            U, S, V = np.linalg.svd(mat2)
            print("U:", U, sep="\n")
            print("S:", S, sep="\n")
            print("V:", V, sep="\n")
    
    elif opt == 12:
        print("Eigen Value: ")
        print("Matrix A: ")
        if m1 != n1:
            print("Not a Square Matrix")
        else:
            result1,result2 = np.linalg.eig(mat1)
            print("Eigen Values: ", result1)
        print("Matrix B: ")
        if m2 != n2:
            print("Not a Square Matrix")
        else:
            result = np.linalg.eig(mat2)
            print("Eigen Values: ", result1)
    
    elif opt == 13:
        k = int(input("Enter the element to search: "))
        print("Matrix A: ", end="")
        check = np.where(mat1 == k, 1, 0)
        check_count = np.count_nonzero(check)
        if check_count > 0:
            print("Found")
        else:
            print("Not Found")
        print("Matrix B: ", end="")
        check = np.where(mat2 == k, 1, 0)
        check_count = np.count_nonzero(check)
        if check_count > 0:
            print("Found")
        else:
            print("Not Found")
    elif opt == 14:
        print("Difference of Sum of Upper and Lower Triangular Matrix: ")
        print("Matrix A: ", end="")
        if m1 != n1:
            print("Not a Square Matrix")
        else:
            print("Difference:", np.sum(np.triu(mat1)) - np.sum(np.tril(mat1)))
        print("Matrix B: ", end="")
        if m2 != n2:
            print("Not a Square Matrix")
        else:
            print("Difference:", np.sum(np.triu(mat2)) - np.sum(np.tril(mat2)))

Welcome to Matrix Calculator

Dimensions of Matrix A (space-separated): 2 2
Enter the elements of Matrix A (2-col, 2-row): 
1 2
3 4

Dimensions of Matrix B (space-separated): 2 2
Enter the elements of Matrix B (2-col, 2-row): 
3 5
6 7

Operations related to Matrix:
  1. Matrix Addition
  2. Matrix Subtraction
  3. Scalar Matrix Multiplication
  4. Elementwise Matrix Multiplication
  5. Matrix Multiplication
  6. Matrix Transpose
  7. Trace of a Matrix
  8. Solve System of Linear Equations
  9. Determinant
 10. Inverse
 11. Singular Value Decomposition
 12. Eigen Value
 13. Search an element in a Matrix
 14. Difference of Sum of Upper and Lower Triangular Matrix
 15. Exit

Enter your choice: 1
Matrix Addition: 
[[ 4  7]
 [ 9 11]]

Enter your choice: 2
Matrix Subtraction: 
[[-2 -3]
 [-3 -3]]

Enter your choice: 3
Enter the scalar value: 4
Scalar Matrix Multiplication: 
Matrix A:
[[ 4  8]
 [12 16]]
Matrix B:
[[12 20]
 [24 28]]

Enter your choice: 5
Matrix Multiplication: 
[[15 19]
 [33 43